# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('login_url', models.URLField()),
                ('username', models.CharField(max_length=200)),
                ('username_label', models.CharField(default='username', max_length=200)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('password_label', models.CharField(default='password', max_length=200)),
                ('success', models.CharField(max_length=255)),
            ],
        ),
    ]
